### ISSUE TITLE
[Question] Routing and Communications.

### ISSUE THREAD

**Issue by KennethanCeyer** [Kotlin/ktor#100]
Hello there.

I am a newbie of Kotlin and Ktor.

I developed a webserver for connecting with a persistence layer that provides via JDBC.

And that server is working fine.

However its routing definition convention seems not good at legibility.

I just wonder What is the best practice to make routing.

For instance, My routing sample code is as follows

```kotlin
routing {
    route("/a") {
        route("/b") {
            post("c") {
                // many logics
            }

            // many route codes
        }

        // many route codes
    }

    route("/d") {
        route("e") {
            post("f") {
                // many logics
            }

            // many route codes
        }

        // many route codes
    }
}
```

When my routing codes are growing up,

This code will occurs many confusing.

I want to make each function corresponding to each route.

This is node express routing code.

```javascript
var express = require('express');

var index = require('./routes/index');
var route = require('./routes/a/index');
var routeAB = require('./routes/a/b');
var routeD = require('./routes/d');

var app = express();

...

app.use('/', index);
app.use('/a/', route);
app.use('/a/b/', routeAB);
app.use('/d/', routeD);
```

This code helps to separate all controller codes to each of directory and files.

Does Ktor support these features?

----

And this is another question.

A documentation of Ktor seems insufficient.

So, I think i will have many questions about Ktor.

Then, Where i can ask that question? (GitHub Issue?, Stackoverflow? or JetBrains community?)

Thank you.

**Comment by orangy** [comment]
You can extract a function from your routing, it's just normal code, you can put it whenever you like. See samples for YouKube and Kweet for some ideas. 

For questions, it's better to ask in kotl.in/slack on #ktor channel.
