### ISSUE TITLE
How to use call.respond in non-suspended function.

### ISSUE THREAD

**Issue by KennethanCeyer** [Kotlin/ktor#101]
Hello there.

I am using ktor 0.3.2 with netty, kotlin1.1 and Java8.

And thank you to make those great framework.

I'm trying to make JDBC middle ware for communication .NET main server via RESTful way.

However i have a problem to `call.respond` in non-suspended function.

```kotlin
post("query") {
    Connection.connect {
         // call.respond occurs an error. (Message: Suspension functions can be called only within coroutine body)
         call.respond(JsonResponse(query("SELECT * FROM someTable").toList())      
    }
}
```

`Connection.connect` function is non-suspended function.

I think the functions as `post()`, `get()` is using lambda function that chanined by pipeline.

And that pipeline is also represented `PipelineContext`, And that function is suspended function.

However `Connection.connect` function can't be implemented pipeline patterns that designed ktor.

How do i solve this problem?

This is the source part of `Connection.connect`.

```kotlin
class Connection private constructor() {
    companion object {
        fun connect(init: Database.() -> Unit): Database {
            return connect("default", init);
        }

        fun connect(name: String, init: Database.() -> Unit): Database {
            var properties: Properties = Properties()
            val config: HashMap<String, Object>? = Config.get(name)

            if (config === null) {
                throw ConfigureNotFoundException("The configuration for connection to JDBC is not founded.")
            }

            DriverManager.registerDriver(com.amazonaws.athena.jdbc.AthenaDriver())
            val conn: Connection = DriverManager.getConnection(
                    config.get("host")?.toString(),
                    config.get("name")?.toString(),
                    config.get("password")?.toString()
            )

            var database = Database(conn)
            database.init()

            return database
        }
    }
}
```

Thank you.

**Comment by KennethanCeyer** [comment]
I solved this issue myself.

Thank you.

**Comment by gavinwilliams** [comment]
@KennethanCeyer would be good let people know what the solution was...

![wisdom_of_the_ancients](https://user-images.githubusercontent.com/611832/38767811-6c2b6850-3fe0-11e8-8bf6-444ed474bc3a.png)

**Comment by KennethanCeyer** [comment]
Hello all you guys

This is very **old** issue...

I almost forgotten what is the problem.. :cry:

However perhaps i had ignored contribution culture at kotlin ecosystem then.

So i would try to remember what the solution was now!


In this issue, The problem was `suspension` function does not support with `post("query")` in follows snippet

```kotlin
post("query") {
    Connection.connect {
         // call.respond occurs an error. (Message: Suspension functions can be called only within coroutine body)
         call.respond(JsonResponse(query("SELECT * FROM someTable").toList())      
    }
}
```

When I looked at Commit in the past, I seem to have solved it like follows.

```kotlin
@location("/athena/query")
data class ControllerName(val credential: Credential, val query: String)

fun Route.controllerName() {
    location<ModelName> {
        method(HttpMethod.Post) {
            handle<ModelName> {
                Connection.connect(it.credential) {
                     call.respond(JsonResponse(query(it.query).toList()))
                }
            }
        }
    }
}
```

**Comment by gavinwilliams** [comment]
Thanks @KennethanCeyer! This lead me down the correct path...

For reference - https://github.com/Kotlin/kotlin-coroutines/blob/master/kotlin-coroutines-informal.md#wrapping-callbacks is the correct way to wrap callbacks within a coroutine and avoid.

> Suspension functions can be called only within coroutine body
