### ISSUE TITLE
Document freemarker module usage

### ISSUE THREAD

**Issue by shinriyo** [Kotlin/ktor#109]
I think the framework uses freemarker as template engine.

I wrote about freemarker `dependencies` of `build.gradle`.

I tried some pattern.

``` 
compile group: 'org.jetbrains.ktor', name: 'ktor-freemarker', version: '0.1.8'
``` 

and

``` 
compile 'org.jetbrains:ktor:0.1.8'
```

Why 0.1.8? I thought only 0.1.8 was available in the URL https://dl.bintray.com/kotlin/ktor/org/jetbrains/ktor-freemarker/0.1.8/

However, I can't import like below
`import org.jetbrains.ktor.freemarker.*`

**Comment by cy6erGn0m** [comment]
@shinriyo you have wrong group name `org.jetbrains`. Should be `org.jetbrains.ktor`. Also note that 0.1.8 is definitely too old: you better to use latest 0.3.2

**Comment by shinriyo** [comment]
@cy6erGn0m thank you for replying.
However, I wrote below in `build.gradle` but I can't import 

```
dependencies {
//    compile "org.jetbrains.ktor:ktor-freemarker:0.3.2"
    compile "org.jetbrains.ktor:freemarker:0.3.2"
}
```

**Comment by orangy** [comment]
You can find proper module names and references here: https://bintray.com/kotlin/ktor/ktor/0.3.2
E.g. for freemarker it would be
```
compile 'org.jetbrains.ktor:ktor-freemarker:0.3.2'
```

**Comment by altavir** [comment]
I have not found any documentation for either freemarker or kotlinx templates. The code is also not documented. The only way to find how to use them is to disassemble tests. Please provide at least a short description in wiki.

**Comment by shinriyo** [comment]
@orangy thank you for response.

I just copied and paste yours. But not work.
It's my whole `build.gradle`.

```
buildscript {
    ext.kotlin_version = '1.1.3'
    ext.ktor_version = '0.3.2'
    ext.ktor_freemarker = '0.1.8'

    repositories {
        mavenCentral()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

apply plugin: 'kotlin'
apply plugin: 'application'

repositories {
    mavenCentral()
    maven { url "https://dl.bintray.com/kotlin/kotlinx" }
    maven { url "https://dl.bintray.com/kotlin/ktor" }
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    runtime "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    compile "org.jetbrains.ktor:ktor-netty:$ktor_version"
    compile 'org.jetbrains.ktor:ktor-freemarker:0.3.2'

    testCompile 'junit:junit:4.11'
    testCompile "org.jetbrains.kotlin:kotlin-test-junit:$kotlin_version"
}

sourceSets {
    main.kotlin.srcDirs += 'src/main/kotlin'
    main.java.srcDirs += 'src/main/java'
}
```

@altavir Yes. I want minimum document.

**Comment by dinomite** [comment]
I created a wee little bit of documentation in [ktor-wiki #12](https://github.com/Kotlin/ktor-wiki/pull/12): https://github.com/dinomite/ktor-wiki/blob/master/Feature-FreeMarker-Templates.md

**Comment by orangy** [comment]
Integrated PR into upcoming doc site
