### ISSUE TITLE
Getting Started Doesn't Work

### ISSUE THREAD

**Issue by base698** [Kotlin/ktor#113]
What are the imports for the getting started app?  Can't see how to import embeddedServer, or routing.  Gradle won't load bintray.com urls from intellij, but resolves on command line.

**Comment by fabienmoritz** [comment]
Indeed, the bintray repo is messed up :sob:

**Comment by tokuhirom** [comment]
Getting started code works fine in my environment with Gradle.
My code is here: https://github.com/tokuhirom/ktor-getting-started/

**Comment by fabienmoritz** [comment]
@tokuhirom it would not if you clear your gradle cache (I recommend not doing it !)

**Comment by cy6erGn0m** [comment]
What artifact exactly it is failing to download?

**Comment by pennadev** [comment]
@cy6erGn0m ktor-core is failing for me

**Comment by cy6erGn0m** [comment]
Do you have repositories specified in your build.gradle? 
What ktor version do you use?
Is the following URL available? https://kotlin.bintray.com/ktor/org/jetbrains/ktor/ktor-core/0.3.2/

Does it fail today? (there were issues at bintray two days ago)

**Comment by fabienmoritz** [comment]
Great, it works ! Thank you 😌

**Comment by base698** [comment]
I think I was also running into this:  https://youtrack.jetbrains.com/issue/IDEA-138029

**Comment by cy6erGn0m** [comment]
Index building failure doesn't block project building, isn't it? 
It's still not clear what are the symptoms, what exactly doesn't work

**Comment by base698** [comment]
Gradle can't access dependencies and because of that I can't build the project.

**Comment by cy6erGn0m** [comment]
Could you please provide error details? error messages?

**Comment by fabienmoritz** [comment]
I use a mutliproject build. I use ktor in a subproject. I had to add the `repositories` info in the `subprojects` section of the parent `build.gradle` to make it resolve the dependency. It works fine in a single project config. I wish we had stuck to maven...

**Comment by orangy** [comment]
Is this problem resolved in the end?
