### ISSUE TITLE
Problems using async

### ISSUE THREAD

**Issue by gabfssilva** [Kotlin/ktor#136]
I'm trying to get a non-blocking function to respond json, but it seems that it does not work:

```kotlin
val user = User(id = UUID.randomUUID().toString(),
        name = "Gabriel",
        birthday = Date(),
        nickname = "Gabriel",
        type = UserType.CLIENT)

val server = embeddedServer(Netty, 8080) {
    install(Routing) {
        get("/api/users") {
            call.findUser()
        }
    }
}

fun main(args: Array<String>) {
    server.start(wait = true)
}

private suspend fun ApplicationCall.findUser() {
    async(CommonPool) { respondText(user.asJson(), Application.Json) }
}
```

When I try to get the resource /api/users, the resource is not found, but, if I remove the "async" call, it works. Can anyone tell what I'm doing wrong?

**Comment by orangy** [comment]
You need to `await` result of `async`.

**Comment by gabfssilva** [comment]
I don't get it, it'd block the thread.

**Comment by orangy** [comment]
No, you won't. If you call `await` on the async, you will _suspend_ the computation, and release the thread, and it will start happily processing other requests. When your async computation finishes, it will resume. However, since `respondText` is also a suspend function and will send a response in a non-blocking sense, I suggest moving `respondText` out of the async block, something like this:

```
respondText(async(CommonPool) { user.asJson() }.await())
```

**Comment by orangy** [comment]
Were you able to resolve an issue?

**Comment by rakshakhegde** [comment]
```
call.respondText(async(CommonPool) { handleLongCalculation(start) }.await())
```

.. from `AsyncApplication` sample did not work. It still waits for the first operation to complete.

**Comment by orangy** [comment]
What do you mean it doesn't work? Of course it should wait for an operation to complete, it should get the result and pass it to `respondText`. But it doesn't block _currently executing thread_, it is released and will handle other connections while `handleLongCalculation` is being executed on the common pool.

**Comment by rakshakhegde** [comment]
I meant, if I make two network requests immediately one after another, the second request takes almost 6 seconds to complete instead of just 3 seconds, like the first request.

**Comment by orangy** [comment]
If you make it from a browser, it is a browser that puts them in queue. Try two different browsers, or curl.

**Comment by rakshakhegde** [comment]
I'm using two tabs, I doubt browser blocks it.

**Comment by orangy** [comment]
It is. There is a reason routing in AsyncApplication is written as `get("/{...}")`
Try opening two tabs with `localhost:8080`, and you'll see first one then second one working sequentially. 
If you open `localhost:8080/1` and `localhost:8080/2` they'll work in parallel. 
If you open dev console, you can see network connection in the second tab for same URL will be in `(pending)` state while first one is working.

**Comment by rakshakhegde** [comment]
What does `{...}` mean?

**Comment by orangy** [comment]
https://github.com/Kotlin/ktor/wiki/Feature-Routing

**Comment by orangy** [comment]
If you have other issues or questions, create separate issues, I will lock this one down. Alternatively, you can join our #ktor on our Slack: slack.kotl.in
