### ISSUE TITLE
receive not working anymore in 0.3.3

### ISSUE THREAD

**Issue by schleinzer** [Kotlin/ktor#139]
While

`val params = call.request.receive<ValuesMap>()`

works fine in 0.3.2, it **only ever returns an empty map in 0.3.3** and so does the new 

`call.receiveParameters()`

(Actually had to revert to 0.3.2 to be able to process any post request).

Am I missing somthing?

Thank you! (LOVING ktor, btw ;-) )

**Comment by orangy** [comment]
It looks like request's content type is not x-www-form-urlencoded or multipart/form-data

**Comment by schleinzer** [comment]
Mhmmm...

I am using jquery like this:

` $.post("/api/some-command", {id: 42})`

and while "id=42" is received in 0.3.2. properly, the same code does not work in 0.3.3. anymore...

**Comment by orangy** [comment]
I did a small test like this:
```
curl -d "param1=value1&param2=value2" -H "Content-Type: application/x-www-form-urlencoded; charset=UTF-8" -X POST http://localhost:8080
```
and added this to HelloApplication
```
        post("/") {
            call.respondText(call.receiveParameters().toString())
        }
```

It prints what is expected:
```
ValuesMap(case=true) [param1=[value1], param2=[value2]]
```

I wonder what could be happening on your side…

**Comment by orangy** [comment]
Did you manage to work it through? Any repro?

**Comment by schleinzer** [comment]
I am very sorry but I am very busy with the project at hand and just reverted to the previous version.

All I can tell is that now the very same code works again without any problems.

And, if this matters, I do use the location feature for the request.

Will try to run some tests once I find some spare time - sorry :-)

**Comment by orangy** [comment]
Okay, I will close it for now. When you have time, repro or just more info, feel free to comment and I will reopen.
