### ISSUE TITLE
Ktor Html Builder not available on Gradle

### ISSUE THREAD

**Issue by rakshakhegde** [Kotlin/ktor#143]

**Comment by orangy** [comment]
Please, specify at least some information and more details about an issue you are having. It's very hard to address reports like this. There is no such a place as "Gradle", it's a build system. All artifacts are published to bintray. ktor-html-builder artifact is there: https://bintray.com/kotlin/ktor/ktor#files/org%2Fjetbrains%2Fktor%2Fktor-html-builder
