### ISSUE TITLE
spring-boot-starter-ktor for Spring Boot as an alternative servlet engine

### ISSUE THREAD

**Issue by loxal** [Kotlin/ktor#154]
Currently I am using `org.springframework.boot:spring-boot-starter-undertow:1.5.4.RELEASE` for my Spring Boot app as a lightweight replacement for Tomcat/Jetty.  

Offering a `spring-boot-starter-ktor` would tremendously increase the popularity of both Kotlin & Ktor! Also people could safely & easily try out the runtime behavior of Ktor and easily compare it to Tomcat / Jetty / Undertow.

**Comment by orangy** [comment]
Hmm, that sounds strange. Why would you host a ktor application inside a Spring servlet, when you can host it directly? Interaction with Spring features is not (easily) possible, so there is not so much value in doing so. If you want an Undertow host, there is a branch where it is prototyped, but it lacks websockets, multipart and http/2 support, hence not merged into master.

**Comment by loxal** [comment]
Ok, thanks for clarification.
