### ISSUE TITLE
Wrong 404 when post data is wrong. Should be 400

### ISSUE THREAD

**Issue by thalescm** [Kotlin/ktor#155]
I don't know what I'm doing wrong, for me it seems that nothing is different from the kweet sample post on login, but when my app configured like this:
```kotlin
@location("/api/accounts")
class PostAccountRequest

fun Route.createAccount() {
    post<PostAccountRequest> {
        call.respondText("Are you trying to create an account?")
    }
}
```
it works:
```
$ curl -X POST localhost:8080/api/accounts -d '{"name":"thales","lastName":"machado"}'
Are you trying to create an account?
```

But when adding data to `PostAccountRequest` it starts giving me 404:
```kotlin
@location("/api/accounts")
data class PostAccountRequest(val name: String = "", val lastName: String = "")

fun Route.createAccount() {
    post<PostAccountRequest> {
        call.respondText("Are you trying to create an account?")
    }
}
```
The response:
```
$ curl -X POST localhost:8080/api/accounts -d '{"name":"thales","lastName":"machado"}'
<H1>404 Not Found</H1><P>Cannot find resource with the requested URI: /api/accounts</P>
```

Can someone help me on what I'm doing wrong here?

**Comment by thalescm** [comment]
Nevermind, sending the post with:
`-H "Content-Type: application/json" ` solved the problem

**Comment by thalescm** [comment]
If I remove the default values on the object, 404 starts happening again:
```kotlin
@location("/api/accounts")
data class PostAccountRequest(val name: String, val lastName: String)

fun Route.createAccount() {
    post<PostAccountRequest> {
        println("name: ${it.name}")
        println("lastName: ${it.lastName}")
        call.respondText("Are you trying to create an account?")
    }
}
```

Response:
```
$ curl -H "Content-Type: application/json"  -X POST localhost:8080/api/accounts -d '{"name":"thales","lastName":"machado"}'
<H1>404 Not Found</H1><P>Cannot find resource with the requested URI: /api/accounts</P>
```

**Comment by orangy** [comment]
Locations feature does not bind post data to parameters, because it cannot be converted back to an URL. Location is something identifying a resource in a strongly typed manner, not a method to to bind json to data classes. So instead of `PostAccountRequest`, you need to have `Accounts` location, and use the same location for get/post, etc. You might also have an `Account(val id: String)` for retrieving account data.

**Comment by thalescm** [comment]
I see, so what is the use of the instance of `PostAccountResuest` that is the parameter of the lambda function on `post`?

**Comment by thalescm** [comment]
Did not really see why using a location over a normal routing, does it do anything else that I'm not getting?

**Comment by orangy** [comment]
Locations are strongly typed hrefs, if you wish. See some examples like https://github.com/Kotlin/ktor/blob/master/ktor-samples/you-kube/src/you/kube/Videos.kt#L39

I need to write a ktor.io article on this…

**Comment by thalescm** [comment]
Ok, thanks for clearing it out!
