### ISSUE TITLE
Function Application.main() -- can't find main class

### ISSUE THREAD

**Issue by GinoHereIam** [Kotlin/ktor#156]
Hi together,

I use the **latest Kotlin and Ktor version** with Gradle.
I want to use Ktor websocket. For beginning I just use the sample. 

My Application.kt
```
fun Application.main() {
    ...
}
```

When I build a fat Jar, it says it can't find the main class. But what's the main class if not `foo.bar.ApplicationKt.main`?

If I create a

```
fun main(){ 
    Application().main()
}
```

It complains that I don't pass **parameter for environment** :((

I guess your sample is broken, because there is no 

```
class ApplicationEnv: ApplicationEnvironment {
    override val classLoader: ClassLoader
        get() = ClassLoader.getSystemClassLoader()
    override val config: ApplicationConfig
        get() = MapApplicationConfig()
    override val log: ApplicationLog
        get() = SLF4JApplicationLog("MyApp")
    override val monitor: ApplicationMonitor
        get() = ApplicationMonitor()
}

fun main(args: Array<String>) {
    Application(ApplicationEnv()).main()
}
```
And how to implement the `ApplicationEnvironment`? There is no documentation!
Can you help me why?  If you need more input, let me know.

Thank you very much. :)
Gino

**Comment by orangy** [comment]
You might want to look into embedded (self-hosted) application documentation : http://ktor.io/getting-started.html#creating-a-self-hosted-application

**Comment by GinoHereIam** [comment]
Oh now I got the issue! The example is written in non-self hosting way! So I would apply it to another webserver! :D Could you update an example websocket + embedded, for noobs like me? :D
