### ISSUE TITLE
Documentation for a self-executable JAR generation. 

### ISSUE THREAD

**Issue by loxal** [Kotlin/ktor#160]
`./gradlew clean jar; java -jar .\build\libs\my.jar`

...gives me...

> Error: Could not find or load main class org.jetbrains.ktor.netty.DevelopmentHost

Otherwise the app runs fine when I do `./gradlew run`. This is my [build.gradle](https://github.com/loxal/muctool/blob/master/build.gradle).

**Comment by rakshakhegde** [comment]
Just create this Gradle `task` for generating a fatjar
```


//create a single Jar with all dependencies
task fatJar(type: Jar) {
	manifest {
		attributes 'Implementation-Title': 'Gradle Jar File Example',
				'Implementation-Version': version,
				'Main-Class': 'org.jetbrains.ktor.netty.DevelopmentHost'
	}
	baseName = project.name + '-all'
	from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
	with jar
}
```
Run `./gradlew fatJar`. You'll have jar under `build/libs/`.

**Comment by loxal** [comment]
@rakshakhegde thanks, this worked for me. I produces pretty much the same result as the `shadowJar` Gradle plugin but I choose your approach over the plugin to reduce external dependencies. 

Now I have the problem that my routing only works when I run `./gradlew run` because of

```
    routing {
        static("/") {
            files("src/main/resources/static") // only works with ./gradlew run but not after fatJar
            // files("static") // does not work in both cases
            // staticRootFolder = File("static") // does not work in both cases either
        }
    }
```
...but this problem is another issue :(

**Comment by orangy** [comment]
Duplicates #141

**Comment by averri** [comment]
The `fatJar`  approach didn't work for me. The final jar has no dependencies inside it.
