### ISSUE TITLE
Maybe better default for charset in respondWrite

### ISSUE THREAD

**Issue by spand** [Kotlin/ktor#161]
Consider if the default value of the charset parameter should be extracted from the content-type header instead of being hardcoded to UTF-8. Something like:
``` 
suspend fun ApplicationCall.respondWrite(charset: Charset = response.headers["content-type"]?.let { ContentType.parse(it).charset() } ?: Charsets.UTF_8, writer: suspend Writer.() -> Unit) {
    respond(WriterContent(writer, charset))
}
```

**Comment by orangy** [comment]
Right, I think we actually need to change it to content-type altogether, and make `respondText` and `respondWrite` be mostly identical in API and defaults.

**Comment by orangy** [comment]
Fixed
