### ISSUE TITLE
Provide a way to externalize application.conf properties

### ISSUE THREAD

**Issue by loxal** [Kotlin/ktor#164]
Configuring SSL requires credentials to be placed inside application.conf.
I want to remove my credentials from an SCM's source code. 
Introduce a way to externalize the configuration of an app, something along the lines of https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

**Comment by orangy** [comment]
You can use HOCON features to do it, see https://github.com/typesafehub/config for more info
