### ISSUE TITLE
ktor-test-host build 0.4.0-alpha-11

### ISSUE THREAD

**Issue by doddi** [Kotlin/ktor#172]
I am new to kotliin and I have been making use of ktor (0.4.0-alpha-11 build)

I am creating an embedded jetty (and also tried netty) server but it will not build because there is a missing transitive dependancy, after including the following in my build:

> testCompile group: 'org.mortbay.jetty.alpn', name: 'alpn-boot', version: '8.1.11.v20170118'

it appears to build correctly.

Below is the error:
`Warning:<i><b>root project 'dojo-interview-test': Unable to build Kotlin project configuration</b>
Details: java.lang.reflect.InvocationTargetException: null
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':testCompileClasspath'.
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find org.mortbay.jetty.alpn:alpn-boot:${alpn.boot.version}.
Searched in the following locations:
    https://repo1.maven.org/maven2/org/mortbay/jetty/alpn/alpn-boot/${alpn.boot.version}/alpn-boot-${alpn.boot.version}.pom
    https://repo1.maven.org/maven2/org/mortbay/jetty/alpn/alpn-boot/${alpn.boot.version}/alpn-boot-${alpn.boot.version}.jar
    https://jcenter.bintray.com/org/mortbay/jetty/alpn/alpn-boot/${alpn.boot.version}/alpn-boot-${alpn.boot.version}.pom
    https://jcenter.bintray.com/org/mortbay/jetty/alpn/alpn-boot/${alpn.boot.version}/alpn-boot-${alpn.boot.version}.jar
    http://dl.bintray.com/jetbrains/spek/org/mortbay/jetty/alpn/alpn-boot/${alpn.boot.version}/alpn-boot-${alpn.boot.version}.pom
    http://dl.bintray.com/jetbrains/spek/org/mortbay/jetty/alpn/alpn-boot/${alpn.boot.version}/alpn-boot-${alpn.boot.version}.jar
    https://dl.bintray.com/kotlin/kotlinx/org/mortbay/jetty/alpn/alpn-boot/${alpn.boot.version}/alpn-boot-${alpn.boot.version}.pom
    https://dl.bintray.com/kotlin/kotlinx/org/mortbay/jetty/alpn/alpn-boot/${alpn.boot.version}/alpn-boot-${alpn.boot.version}.jar
    https://dl.bintray.com/kotlin/ktor/org/mortbay/jetty/alpn/alpn-boot/${alpn.boot.version}/alpn-boot-${alpn.boot.version}.pom
    https://dl.bintray.com/kotlin/ktor/org/mortbay/jetty/alpn/alpn-boot/${alpn.boot.version}/alpn-boot-${alpn.boot.version}.jar
    http://central.maven.org/maven2/org/mortbay/jetty/alpn/alpn-boot/${alpn.boot.version}/alpn-boot-${alpn.boot.version}.pom
    http://central.maven.org/maven2/org/mortbay/jetty/alpn/alpn-boot/${alpn.boot.version}/alpn-boot-${alpn.boot.version}.jar
Required by:
    project : > org.jetbrains.ktor:ktor-test-host:0.4.0-alpha-11</i>`

**Comment by loxal** [comment]
Got the same error going from alpha-10 to alpha-11, resolved it by adding 

> testCompile "org.mortbay.jetty.alpn:alpn-boot:8.1.11.v20170118"

to my build.gradle.

**Comment by mkporwit** [comment]
Getting the same error trying to update from 0.3.3 to 0.4.0-alpha-13:
```Warning:<i><b>root project 'documentid-server': Unable to build Kotlin project configuration</b>
Details: java.lang.reflect.InvocationTargetException: null
Caused by: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':testCompileClasspath'.
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find org.mortbay.jetty.alpn:alpn-boot:${alpn.boot.version}.
Searched in the following locations:
    https://jcenter.bintray.com/org/mortbay/jetty/alpn/alpn-boot/${alpn.boot.version}/alpn-boot-${alpn.boot.version}.pom
    https://jcenter.bintray.com/org/mortbay/jetty/alpn/alpn-boot/${alpn.boot.version}/alpn-boot-${alpn.boot.version}.jar
    https://dl.bintray.com/kotlin/kotlinx/org/mortbay/jetty/alpn/alpn-boot/${alpn.boot.version}/alpn-boot-${alpn.boot.version}.pom
    https://dl.bintray.com/kotlin/kotlinx/org/mortbay/jetty/alpn/alpn-boot/${alpn.boot.version}/alpn-boot-${alpn.boot.version}.jar
    https://dl.bintray.com/kotlin/ktor/org/mortbay/jetty/alpn/alpn-boot/${alpn.boot.version}/alpn-boot-${alpn.boot.version}.pom
    https://dl.bintray.com/kotlin/ktor/org/mortbay/jetty/alpn/alpn-boot/${alpn.boot.version}/alpn-boot-${alpn.boot.version}.jar
Required by:
    project : > org.jetbrains.ktor:ktor-test-host:0.4.0-alpha-13</i>```

**Comment by cy6erGn0m** [comment]
Should be fixed now. Please reopen if you see it again.
