### ISSUE TITLE
ktor-test-host with gson

### ISSUE THREAD

**Issue by doddi** [Kotlin/ktor#173]
I am unable to test an endpoint that has been configured to use the GsonSupport available in the latest 0.4.0-alpha-11 build.

Using an embedded netty server I have the following:

```
fun Application.server() {
    install(DefaultHeaders)
    install(CallLogging)
    install(GsonSupport) {
        setPrettyPrinting()
    }
    routing {
        get("/all") {
            call.respond(productResource.getAll())
        }
    }
}
```

testing it with ktor-test-host:

```
              withTestApplication(Application::server) {
                    with(handleRequest(HttpMethod.Get, "/all")) {
                        assertEquals(HttpStatusCode.OK, response.status())
                    }
                }
```

I get the following partial stack trace:

> Response pipeline couldn't transform 'class java.util.ArrayList' to the FinalContent
> java.lang.IllegalArgumentException: Response pipeline couldn't transform 'class java.util.ArrayList' to the FinalContent
> 	at org.jetbrains.ktor.host.BaseApplicationCall$$special$$inlined$apply$lambda$1.doResume(BaseApplicationCall.kt:33)
> 	at org.jetbrains.ktor.host.BaseApplicationCall$$special$$inlined$apply$lambda$1.invoke(BaseApplicationCall.kt)
> 	at org.jetbrains.ktor.host.BaseApplicationCall$$special$$inlined$apply$lambda$1.invoke(BaseApplicationCall.kt:15)
> 	at org.jetbrains.ktor.pipeline.PipelineContext$proceed$1.doResume(PipelineContext.kt:29)
> 	at org.jetbrains.ktor.pipeline.PipelineContext.proceed(PipelineContext.kt:21)
> 	at org.jetbrains.ktor.pipeline.Pipeline.execute(Pipeline.kt:22)
> 	at org.jetbrains.ktor.response.ApplicationResponseFunctionsKt$respond$1.doResume(ApplicationResponseFunctions.kt:11)
> 	at org.jetbrains.ktor.response.ApplicationResponseFunctionsKt.respond(ApplicationResponseFunctions.kt:10)
> 	at ServerKt$server$2$2.doResume(Server.kt:26)
> 	at ServerKt$server$2$2.invoke(Server.kt)
> 	at ServerKt$server$2$2.invoke(Server.kt)
> 	at org.jetbrains.ktor.pipeline.PipelineContext$proceed$1.doResume(PipelineContext.kt:29)

However my application does work and correctly responds json data when accessed from the endpoint

**Comment by orangy** [comment]
gson support only kicks in when `Accept` header is indicating that `application/json` is allowed. Browser sends it, but your test doesn't.

**Comment by shalva97** [comment]
The issue mentions Gson, but will post here since the error is same for me on kotlin serialization.

so what was the solution to this? I have followed [codumentation ](https://ktor.io/docs/creating-http-apis.html#automated-testing) and they also do not pass any extra header, but it just works in their example. 

In my new project I can not get it to work. I have tried adding header, but still same error
```kotlin
handleRequest(HttpMethod.Get, "/myRoute") {
   this.addHeader("Content-Type", "application/json")
}
```

**Comment by Stexxe** [comment]
@shalva97 could you please [file a new issue](https://youtrack.jetbrains.com/newIssue?project=KTOR) with a code snippet for reproducing attached?

**Comment by shalva97** [comment]
my bad, I had added `install(ContentNegotiation) { json() }` to the embededServer. it was not being used by tests because I was only  testing the route directly, so in s hort I was bypassing the negotiation....

all good now,  thanks for response
