### ISSUE TITLE
respond(someClass) causes Internal Server Error without appropriate accept header

### ISSUE THREAD

**Issue by robotlovesyou** [Kotlin/ktor#180]
If I have something like...
```
data class GreetMe(val firstname: String, val lastname: String, val title: String)
data class Greeting(val greeting: String)

@location("/formalGreeting") class formalGreeting()

fun Application.main() {
    install(DefaultHeaders)
    install(GsonSupport)
    install(Locations)
    install(Routing) {
        post<formalGreeting> {
            val greet = call.receive<GreetMe>()
            val greeting = Greeting("Hello ${greet.title} ${greet.firstname} ${greet.lastname}")
            call.respond(greeting)
        }
    }
}
```
...and I call it *without* an appropriate Accept header (eg application/json) then I'll get a 500 error along the lines of `IllegalArgumentException: Response pipeline couldn't transform 'class Greeting' to the FinalContent`

Calling it with an appropriate Accept header results in the expected behaviour

I tried setting the content type of the response with `call.response.header("Context-Type", "application/json")` but it did not stop the 500 error occurring

I'm probably doing (or not doing) something which would prevent this behaviour but if that isn't the case then I don't think a missing Accept header should result in a 500 error. For me a 500 error should be an indication of something wrong in *my* API implementation. I shouldn't be seeing it just because a client forgets to add a specific header to the request.

**Comment by orangy** [comment]
Right, it should be `400 Bad Request`, i.e. a client-side error code. This is planned for proper content-negotiation feature which we will start working on right after 0.4.0 is out, see #167

**Comment by robotlovesyou** [comment]
OK. That's good to know.

Thanks 

:)

**Comment by orangy** [comment]
Duplicates #167
