### ISSUE TITLE
Netty: error with old instances of Application after code reload

### ISSUE THREAD

**Issue by kosiakk** [Kotlin/ktor#181]
I've modified `Hello (Netty)` example to request an application feature in get handler:
https://gist.github.com/kosiakk/fa2298f62e151baffbf4ae32a7833711

To reproduce: 
- Modify the original demo example to call `application.feature`
- Start the demo (Debug, Windows, JDK 1.8.0_144) and open a page
- Change something like "Hello, World **5**!" and compile the code
- Refresh the page (and favicon) using Ctrl-F5 on Chrome 
- Several clicks must be required to trigger the restart (_why?!_)

Switching back to `ktor-v0.4.0-alpha-11` resolves the problem.

What's different between ktor-v0.4.0-alpha-11 and -12:
- In later versions `Application - Changes in application detected.` is shown **before** "Processing get". To me this looks like a symptom of improper locking.
- Previous versions sometimes locked the class-files and compilation was failing (maybe if execution was on the breakpoint), and I haven't experienced this problem after alpha-12. But I am not 100 % confident.
- Changes between versions (https://github.com/Kotlin/ktor/compare/build-0.4.0-alpha-11...build-0.4.0-alpha-12) included `DispatcherWithShutdown` - which seems to be involved in the restart process with `Application stopping` messages, but I was not able to debug it properly.

**Comment by kosiakk** [comment]
It seems that AutoReload feature was broken between 0.4.0-alpha-11 and 12. It is always reproduced in my app, whith the Ktor version being the only change. After version 12, the app restarts as usual, but all `install` calls get lost. Therefore any call to `application.feature` fails with `java.lang.IllegalStateException: No instance for key AttributeKey: x`. What I can see, is that `attributes[ApplicationFeature.registry]` is empty after restart, although routing seems to work well. 

The lastest alpha-14 is also failing in the same way, with no obvious problems shown in log. The most surprising thing is that after _another_ change of the code, the app can actually recover! So it seems like some recently introduced race condition in the framework.

**Comment by orangy** [comment]
Weirdly enough it does work for me. What's are your watchkeys?

**Comment by orangy** [comment]
As a side note, `application.log` is what you can use, I will lock down (make private) `CallLogger` property for log and monitor.

**Comment by kosiakk** [comment]
As log says, it is unchanged from the sample:
```
ktor {
    deployment {
        port = 8080
        watch = [ hello ]
        autoreload = true
    }

    application {
        modules = [ org.jetbrains.ktor.samples.hello.HelloApplicationKt.main ]
    }
}
```
Complete steps:
- take ktor code from Github
- add maven project
- specify jdk8
- add one line to `org.jetbrains.ktor.samples.hello.HelloApplication`, to the `get` handler:
```
call.application.feature(CallLogging).toString()
```
- run `Ktor :: Json (Netty)`
- open `http://localhost:8080/` in Chomre
- change `respondText("Hello, World 2!")` and **Build project**
- switch to web page and click F5 or even Ctrl-F5
- Observe `java.lang.IllegalStateException: No instance for key AttributeKey: Call Logging`

Try changing the code several times, if you see the updated message every time.

**Comment by orangy** [comment]
It just works for me :( What's your platform?

**Comment by kosiakk** [comment]
I see the same problem on two my computers, with similar configuration. 
One of them is: Windows 10 build 1703, Chrome 60
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode).

Try holding F5 - this will send several dozen requests. *Sometimes* (I hate that, too) the app recovers, so you'll see the problem only in the stdout.

**Comment by orangy** [comment]
I believe that could a problem with file system watchers. What if you wait a little bit longer after a rebuild? I'm on a Mac and it works fine here.

**Comment by kosiakk** [comment]
What happens is that `call.application` in the get handler gets an **old instance** of `Application`, which was destroyed (and its Attributes is empty). I see that a correct instance of `Application` is returned from `ApplicationHostEnvironment`, an old (wrong) instance is cached somewhere. I've made a memory dump, proving my point. There are hundreds of orphan objects, referring to the old Application. Can it be cached in the Channel somewhere? E.g. by pre-constructing `NettyHostHttp1Handler`?

**Comment by orangy** [comment]
Fixed
