### ISSUE TITLE
Generate URIs from routes / reverse routing?

### ISSUE THREAD

**Issue by msheakoski** [Kotlin/ktor#184]
In templates, APIs, and HTTP redirects, it is useful to be able to use named routes which generate URIs that point to other parts of the app. Is this something planned for ktor's router or is there a current recommended best practice for keeping URI management simple?

Some examples:
* https://www.playframework.com/documentation/2.6.3/JavaRouting#Reverse-routing (different approach than the following examples)
* https://github.com/alexmingoia/koa-router/tree/master#module_koa-router--Router+url
* https://symfony.com/doc/current/components/routing.html#generate-a-url

**Comment by orangy** [comment]
Yes, see `Locations` feature. Unfortunately, it's not documented yet, so see tests and samples.
