### ISSUE TITLE
DDoS by OutOfMemoryError with 64MB heap & 1000 concurrent users

### ISSUE THREAD

**Issue by loxal** [Kotlin/ktor#199]
I've started [this Ktor powered app](https://github.com/loxal/muctool) in a Docker container and assigned the app a heap of just 64 MB*. Running a JMH throughput load test yield good numbers with 100 threads. However running the same tests with 1000 DDoSed** the app and I got 

> java.lang.OutOfMemoryError: GC overhead limit exceeded
> java.lang.OutOfMemoryError: GC overhead limit exceeded
> java.lang.NoClassDefFoundError: Could not initialize class ch.qos.logback.classic.spi.ThrowableProxy
>         at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:119)
>         at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:419)
>         at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
>         at ch.qos.logback.classic.Logger.log(Logger.java:765)
>         at org.eclipse.jetty.util.log.JettyAwareLogger.log(JettyAwareLogger.java:607)
>         at org.eclipse.jetty.util.log.JettyAwareLogger.warn(JettyAwareLogger.java:431)
>         at org.eclipse.jetty.util.log.Slf4jLog.warn(Slf4jLog.java:69)
>         at org.eclipse.jetty.util.log.Slf4jLog.warn(Slf4jLog.java:64)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:648)
>         at java.lang.Thread.run(Thread.java:748)
> Exception in thread "qtp489279267-62" java.lang.NoClassDefFoundError: Could not initialize class ch.qos.logback.classic.spi.ThrowableProxy

from which the app could not recover. What I would expect is more resiliency. An app with 64 MB cannot handle 1000 concurrent users and that's ok but the app should not be irrecoverably DDoSed when 1000 users try to use it.

**Unlike from a regular exception a Java app is not expected to recover or catch an Error. However maybe there is way to prevent this error altogether by not allowing any further connections**?

*32 MB heap work just fine too
**load test was run from a mobile internet connection

**Comment by orangy** [comment]
While this is a valid point, I'm not sure at this point we can do much about it. If you get a pure Jetty application (primitive servlet or something) without any ktor, I believe the result will be the same. Would be nice if you could check it.

**Comment by loxal** [comment]
I switched to Netty by changing just two lines inside my `build.gradle` and this time the load tests timed out but the service did not crashed and kept up and running. However the throughput dropped 2x as the default thread pool for Netty is just 6 threads instead of Jetty's 100+ threads.

**Comment by orangy** [comment]
I suspect 100+ threads is too much for 32MB heap. We will add more configuration to hosts soon, so that you will be able to tune threads to your needs.
