### ISSUE TITLE
Any ideas for the model layer?

### ISSUE THREAD

**Issue by alexeypetrushin** [Kotlin/ktor#204]
Examples looks nice! But I haven't found anything to model business logic or work with DB. 

Do you have any plans to provide that too? There's Hibernate of course, but it's old and ugly. Would be nice to have something like RoR ActiveRecord...

**Comment by orangy** [comment]
We don't have to do anything with DB, you can use whatever you want, either Java (e.g. hibernate, jooq) or check http://kotlin.link for DB section.
