### ISSUE TITLE
How to retrieve value for WebSocket routing path parameter

### ISSUE THREAD

**Issue by frendyxzc** [Kotlin/ktor#207]
Can ktor support to attach param when using websocket?

I find it will be parsed in RoutingBuilder.kt as follow, but how to get the param?

    fun Route.createRoute(path: String): Route {
                ...
                RoutingPathSegmentKind.Parameter -> UriPartParameterBuilder.parse(value)

    install(Routing) {
        webSocket("/ws/{param}") {
            ????  How to get the param “room01” in "ws://10.1.1.1:8080/ws/room01"
        }
    }

**Comment by orangy** [comment]
`call.parameters["param"]` should work

**Comment by frendyxzc** [comment]
thank you, but when the path set as "/ws/{param}", it cannot be connected...

install(Routing) {
    webSocket("/ws/{param}") {

2017-09-18 17:26:41.832 [nettyCallPool-4-2] TRACE Application - Unhandled: GET - /ws

**Comment by orangy** [comment]
Right, the request was for `/ws` and should be for `/ws/somethinghere`. If parameter is optional, use `{param?}`

**Comment by frendyxzc** [comment]
@orangy Yes, thank you... But it still cannot connected... Do i miss something?

My request in JS file is such as follow:

```
function connect() {
    socket = new WebSocket("ws://" + window.location.host + "/ws/room100");
```

And on sever, I modify as:

```
install(Routing) {
    webSocket("/ws/{param?}") {
```

**Comment by cy6erGn0m** [comment]
Just tried the same in ChatApplication sample and it seems to work perfect 

```
        webSocket("/ws/{param?}") {
            println(call.parameters["param"])
```

@frendyxzc  Do you see any messages in app log? any javascript errors in devconsole?

**Comment by frendyxzc** [comment]
@orangy @cy6erGn0m Yep, it's work!!! Thank you very very much, I guess it failed to connect because of the cache of browser with a wrong js... Thank you..
