### ISSUE TITLE
Each second response is delayed

### ISSUE THREAD

**Issue by devulex** [Kotlin/ktor#213]
For example, 336ms, 9ms, 314ms, 8ms, 332ms, 9ms...
The problem can be seen in [kotlin-fullstack-sample](https://github.com/Kotlin/kotlin-fullstack-sample), where ktor 3.0.0 and embedded Jetty instance are used. Similar behavior in version 4.0.0. The delay is repeated strictly every second time and does not depend on the request.
I run server with `gradlew backend: run`. OS Win 10.

**Comment by cy6erGn0m** [comment]
What client do you use?  Is it browser or curl ?

**Comment by devulex** [comment]
The problem is repeated when using any client. I checked in the browser and Postman. For example, the application on Spring processes all requests without delay.

**Comment by orangy** [comment]
What if you don't install `DefaultHeaders`? Does it help to get rid of delay?

**Comment by devulex** [comment]
DefaultHeaders are installed:
https://github.com/Kotlin/kotlin-fullstack-sample/blob/f76a0a82a07f546bbb6b5476a6b1a7e80f35a62a/backend/src/org/jetbrains/demo/thinkter/Application.kt#L21

Now I started the project on another machine (also Win 10) and the problem repeats.

**Comment by orangy** [comment]
Yes, I mean if you *don't* install DefaultHeaders, would it help?

**Comment by orangy** [comment]
This is the only place I can think of having something happening every second:
https://github.com/Kotlin/ktor/blob/master/ktor-core//src/org/jetbrains/ktor/features/DefaultHeaders.kt#L39

But 300ms looks like too much for date/time stringify…

**Comment by devulex** [comment]
I tried not to use `DefaultHeaders` - delay also exists.

**Comment by devulex** [comment]
Sergey, did you manage to reproduce this problem?

**Comment by cy6erGn0m** [comment]
@devulex Can't reproduce it
Which url do you query? Do you call it through webpack dev server or directly (which port)? Couldn't it be some kind windows issue (Windows Defender maybe?)?

You also can try to switch to Netty (just replace ktor-host-jetty to ktor-host-netty and Jetty to Netty in kotlin file)

**Comment by devulex** [comment]
Delay appears at any address, for example, index `http://localhost:8080`. But only when you use dev server port `kotlinFrontend.webpackBundle.port`. When addressing directly everything is fine. Maybe problem is in frontend plugin?

**Comment by devulex** [comment]
Disabling defender Windows did not help. I want to note that problem was repeated on two different computers running Win 10.

**Comment by cy6erGn0m** [comment]
Then this delay is caused by dev server or webpack or some plugin. In production configuration it should always work directly so it's not so serious. For sure it is not ktor-related issue

**Comment by devulex** [comment]
Thank you for your time.
