### ISSUE TITLE
SessionSerializerReflection not supported type

### ISSUE THREAD

**Issue by monarezio** [Kotlin/ktor#214]
When I have a object that has an array of strings or any other object it throws and error that its not supported...

`data class Messages (var messages: Array<String> = arrayOf())`

`call.sessions.set(SessionKeys.MESSAGE, Messages(arrayOf()))`

but if I had only a string as the parameter of the class Messages it worked fine...

`data class Messages (var messages: String = "")`

**Comment by orangy** [comment]
Avoid using Arrays whenever possible, there are too many issues with them. In sessions, `List`, `Set` and `Map` are supported.

**Comment by monarezio** [comment]
Ok, cheers!
