### ISSUE TITLE
One more issue about deploying

### ISSUE THREAD

**Issue by vellrya** [Kotlin/ktor#216]
Hello! I have already seen several similar issues, but I have not found a solution in any of them. I created a server based on Netty, which successfully runs in Idea. I'm trying to get a jar, but I see an error about the absence of the main class. How can I start the server without Idea. Thank you in advance)

**Comment by orangy** [comment]
Did you check the guide? http://ktor.io/getting-started.html#creating-a-self-hosted-application

**Comment by vellrya** [comment]
Of course, but there is no information about running the server without Idea. But the launch in it I set up according to this manual

**Comment by orangy** [comment]
That's normal application, not different to a console app. You can use `application` plugin in Gradle and use `./gradlew run`. Or just `java -jar` after you built it. Also see Docker doc about how to package a single jar: http://ktor.io/getting-started-docker.html#package-an-application

**Comment by vellrya** [comment]
I'm using maven. I'm trying to compile jar, but I get the following error: Main method not found in class *, please define the main method... 

But my main class contains only this, as in the example: fun Application.main () {
install(...)
...
}

**Comment by devulex** [comment]
@vellrya , I recently solved a similar problem.
I recommend to take as a basis [kotlin-fullstack-sample](https://github.com/Kotlin/kotlin-fullstack-sample)

Below is an example for running backend.
You must add a task to copy all the dependencies and artifacts to the directory (for example, lib).
```gradle
task install(type: Copy) {
    dependsOn build
    from configurations.runtime
    from jar
    into "${project.projectDir}/lib"
}
```
Run the backend with the command
`java -classpath "lib\backend-0.0.1-SNAPSHOT.jar;lib\*" org.jetbrains.ktor.jetty.DevelopmentHost`

You can also create `META-INF/MANIFEST.MF` so as not to indicate the classpath and the main class at command line:
```gradle
jar {
    manifest {
        attributes("Class-Path": configurations.compile.collect { it.getName() }.join(' '),
                "Main-Class": "org.jetbrains.ktor.jetty.DevelopmentHost")
    }
}
```
In this case, the launch is performed by the command:
`java -jar lib\backend-0.0.1-SNAPSHOT.jar`

**Comment by vellrya** [comment]
Thanks a lot)

**Comment by Ethras** [comment]
got the same issue with io.ktor:ktor-server-netty:0.9.1 
saying main class could not be found in io.ktor.server.netty.DevelopmentEngine
