### ISSUE TITLE
Add Grouping/Series in HttpStatus

### ISSUE THREAD

**Issue by triplem** [Kotlin/ktor#220]
For some use cases it is necessary to group HttpStatusCodes (eg. 1xx to Informational, 2xx to Successful, ...). This could be done in the user of this Object, but I guess it would be beneficial to implement this directly in the HttpStatusCode.

**Comment by triplem** [comment]
This could be done in multiple ways. The easiest is to add another property (group) which returns another enum for the group of the status. This could be done using a regex on the value of the Status.
Another way would be to add a new object which determine directly from the status. 

A possible use case would be an aggregation of responses in the metrics feature.

**Comment by cy6erGn0m** [comment]
```
enum class HttpStatusCategory {
    Informational, Successful, ....
}

val HttpStatusCode.category: HttpStatusCategory
    get() = when (value) {
        in 100..199 -> HttpStatusCategory.Informational
....
    }
```

?

**Comment by triplem** [comment]
Perfect. Thanks.
