### ISSUE TITLE
Clean various `parameters` API

### ISSUE THREAD

**Issue by orangy** [Kotlin/ktor#30]
* do not use host's parameters API
* parse query parameters manually on all hosts
* rename ApplicationRequest.parameters → queryParameters
* Use request.content.get<FormData>() to get form parameters
* `ApplicationCall.values` (renamed from parameters) should combine them all
    * routing adds own path-bound parameters

**Comment by cy6erGn0m** [comment]
branch [query.parameters](/Kotlin/ktor/commits/query.parameters)
