### ISSUE TITLE
Clean `response` API

### ISSUE THREAD

**Issue by orangy** [Kotlin/ktor#31]
On an `ApplicationCall` there are 
- `response` property which is ApplicationResponse
- `respond` property which is ResponsePipeline
- `respond` function which executes a subject on a pipeline

We need to figure our better non-confusing APIs.

**Comment by cy6erGn0m** [comment]
At first, I've moved `respond: RespondPipeline` to `ApplicationResponse.pipeline`. So now we have `response` and `respond()` in call.
