### ISSUE TITLE
CSRF protection

### ISSUE THREAD

**Issue by orangy** [Kotlin/ktor#35]
https://www.owasp.org/index.php/Cross-Site_Request_Forgery_%28CSRF%29_Prevention_Cheat_Sheet

**Comment by kiru** [comment]
Why is this issue closed?

**Comment by Stexxe** [comment]
@kiru I've created a [feature request](https://youtrack.jetbrains.com/issue/KTOR-2910) in YouTrack that you can follow.

**Comment by QuinnBast** [comment]
But the youtrack is closed? There is no links to any MRs and there is not any documentation to indicate that ktor supports CSRF tokens

**Comment by Stexxe** [comment]
It's closed because the feature has been implemented. You can find the pull requests in the history of the YouTrack issue (https://github.com/ktorio/ktor/pull/3847).
