### ISSUE TITLE
Missing Accept header should match any header("Accept", "…") selector

### ISSUE THREAD

**Issue by orangy** [Kotlin/ktor#38]
From spec https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

> If no Accept header field is present, then it is assumed that the client accepts all media types.

**Comment by aeronite** [comment]
Does this mean that by default in Ktor 0.9.1 an http Get request without an 'Accept' header will be handled successfully? My client apps get 406 responses and I can't see a way around this in the ktor server code
