### ISSUE TITLE
`TODO()` should map to 501 rather than 500

### ISSUE THREAD

**Issue by rocketraman** [Kotlin/ktor#49]
If a route is implemented with a Kotlin `TODO()`, currently ktor returns a `500 Server Error`. It should return a `501 Not Implemented`.

**Comment by orangy** [comment]
You need to add errorPage handler to application for this to work:
```
    errorPage { 
      if (it is NotImplementedError)
        call.respond(HttpStatusCode.NotImplemented)
    }
```

**Comment by rocketraman** [comment]
Ah, that's very nice. I was initially thinking that ktor should have reasonable defaults, such as handling `NotImplementedError` automatically, but now I wonder if being more explicit is actually better.

**Comment by orangy** [comment]
This is being refactored, btw, there will be an installable feature with more config:
```
            application.install(StatusPages) {
                statusFile(HttpStatusCode.NotFound, HttpStatusCode.NotImplemented, filePattern = "error#.html")
                exception<IllegalStateException> { cause ->
                    call.respond(TextContentResponse(HttpStatusCode.InternalServerError, ContentType.Text.Plain.withCharset(Charsets.UTF_8), cause.javaClass.simpleName))
                }
            }
```

**Comment by orangy** [comment]
I think this can be closed? @rocketraman

**Comment by rocketraman** [comment]
Yup, closed!
