### ISSUE TITLE
Simplify the Automatic HEAD response feature

### ISSUE THREAD

**Issue by gzoritchak** [Kotlin/ktor#59]
The Readme.md indicates an _[Automatic HEAD response](https://github.com/Kotlin/ktor/blame/master/README.md#L59)_. It's not as automatic as one could expect. It needs the installation of HeadRequestSupport feature AND the routing of HEAD requests.

This feature: 

1. should be at least documented, 
2. ideally, easier to set up (with automatic Head handles for every get).

As a workaround to set up the Head routing for every Get mapping, you can add this extension method:
```
fun Route.getOrHead(path: String, body: PipelineContext<ApplicationCall>.(ApplicationCall) -> Unit): Route {
    val selector = OrRouteSelector(HttpMethodRouteSelector(HttpMethod.Get),HttpMethodRouteSelector(HttpMethod.Head))
    return select(selector).route(path) { handle(body) }
}
```
and replace the get calls by this new function.

```
install(HeadRequestSupport)
routing {
    getOrHead("/foo") {
        call.respondText("Bar")
    }
}
```

**Comment by orangy** [comment]
Fixed.
