### ISSUE TITLE
CPU at 100% due to Compression feature

### ISSUE THREAD

**Issue by gzoritchak** [Kotlin/ktor#60]
I didn't manage to reproduce it in a dev/integration environment but I had it in production. 
The Compression feature was taking all CPU. Removing it resolved the problem.

The configuration of the feature was: 

```
    install(Compression) {
        default()
        excludeMimeTypeMatch(ContentType.Video.Any)
    }

```

See above the view of the threads and the profiling of CPU.

![image](https://cloud.githubusercontent.com/assets/1110254/21519191/8f420c9a-cceb-11e6-82f3-7f77e89480cb.png)

![image](https://cloud.githubusercontent.com/assets/1110254/21519168/6e5059b0-cceb-11e6-91da-fa46500abc63.png)

**Comment by cy6erGn0m** [comment]
Is the content on client side valid (status, not corrupted content)? Could you please check response headers (to ensure `Content-Encoding: gzip` and there is no `gzip, gzip` or something like that)

**Comment by gzoritchak** [comment]
Sorry but, I never managed to reproduce it in a controlled environment. I tried to do a full crawl of all pages, and resources, but everything worked as expected.

It happened very often in production environment with unknown clients (our prospects or customers). I had to resolve the problem urgently so I removed the Compress support.

**Comment by orangy** [comment]
Since there is no repro and underlying engine has since been rewritten, I'm closing this issue.
