### ISSUE TITLE
html-builder should log errors

### ISSUE THREAD

**Issue by gzoritchak** [Kotlin/ktor#61]
The current implementation of html-builder uses an HTMLStreamBuilder to produce html through kotlinx.html library. 

HTMLStreamBuilder is a TagConsumer that uses the default ```onTagError``` implementation : https://github.com/Kotlin/kotlinx.html/blob/master/shared/src/main/kotlin/api.kt#L14

In case of an exception in a bloc that produces html, nothing is logged and a empty html page is returned to the client. 

To simplify debugging, in case of error or exception a trace should be logged.

**Comment by orangy** [comment]
I think this has been fixed, can you confirm?
