### ISSUE TITLE
LocalFileContent causes browser cache without allowing Cache Control

### ISSUE THREAD

**Issue by gzoritchak** [Kotlin/ktor#63]
The current implementation of LocalFileContent : 

- adds a LastModified header which cause browser cache (https://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html#sec13.2.4),
- but set CacheControl header to null, making impossible to set the max-age of the resource.

During active development of a web site, users can have an inconsistent view of the site: pages with old css and js scripts.

**Comment by cy6erGn0m** [comment]
@gzoritchak Why don't you simply intercept and wrap LocalFileContent with your best max-age settings?

**Comment by cy6erGn0m** [comment]
the other alternative is to provide constructor parameters expires and cache control

**Comment by gzoritchak** [comment]
@cy6erGn0m 

> Why don't you simply intercept and wrap LocalFileContent with your best max-age settings?

I first tried to put a global interception : 

`        intercept(ApplicationCallPipeline.Infrastructure) {
            if (call.request.httpMethod == HttpMethod.Get ||
                    call.request.httpMethod == HttpMethod.Head) {
                call.response.cacheControl(CacheControl.MaxAge(300))
            }
        }
`
It put the Cache-control header to all requests except the ones served by LocalFileContent.

> the other alternative is to provide constructor parameters expires and cache control

I didn't see any constructor in LocalFileContent that give access to cacheControl property.

**Comment by gzoritchak** [comment]
My bad: the global interception is working.

In fact I have now 2 Cache-Control http header for one request!!

**Comment by cy6erGn0m** [comment]
@gzoritchak in a simple case I see no double cache control header

**Comment by gzoritchak** [comment]
@cy6erGn0m  

1. Thanks for your modifications on LocalFileContent to allow CacheControl. 
2. In your test, adding cache control to the LocalFileContent doubles the header. It should not be possible (https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2)

> Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma.


```    @Test
    fun testInterceptCacheControl() {
        withTestApplication {
            application.intercept(ApplicationCallPipeline.Infrastructure) { call ->
                if (call.request.httpMethod == HttpMethod.Get ||
                        call.request.httpMethod == HttpMethod.Head) {
                    call.response.cacheControl(CacheControl.MaxAge(300))
                }
            }

            application.intercept(ApplicationCallPipeline.Call) { call ->
                call.respond(LocalFileContent(
                        File(basedir, "org/jetbrains/ktor/tests/http/StaticContentTest.kt"),
                        cacheControl = CacheControl.MaxAge(200)
                ))
            }
```

**Comment by cy6erGn0m** [comment]
Don't think we can eliminate double headers: to achieve this we have to keep and maintain a list of single values only headers that doesn't look good

**Comment by gzoritchak** [comment]
I'm not sure. 

The specification gives a general rule that can be applied. It's not an implementation based like "THIS particular header can be duplicated and THAT one not".
