### ISSUE TITLE
Httpbin sample

### ISSUE THREAD

**Issue by jmfayard** [Kotlin/ktor#73]
Hello,

I am implementing [here](https://github.com/jmfayard/ktor/blob/httpbin/ktor-samples/ktor-samples-httpbin/src/org/jetbrains/ktor/samples/httpbin/HttpbinApplication.kt) a ktor version of [https://httpbin.org/](https://httpbin.org/) `HTTP Request & Response Service` 

It's nowhere done, but I wanted to know if there is some interest that I eventually contribute it as a ktor sample.

   Jean-Michel

**Comment by orangy** [comment]
Wow, great, thanks! That would be a nice base for some docs and samples.

**Comment by jmfayard** [comment]
see #74
