### ISSUE TITLE
Don't pull in logback-classic as a dependency

### ISSUE THREAD

**Issue by sanity** [Kotlin/ktor#75]
A number of ktor gradle artifacts specify logback-classic as a dependency, however best practice for libraries is to include something like sl4j-api, but not any specific logging implementation - to prevent an application's logs from being filled up with logging generated by a library.

The workaround is to do something like this:

```groovy
    compile ('org.jetbrains.ktor:ktor-core:0.3.0') {
        exclude group : 'ch.qos.logback', module : 'logback-classic'
    }
```

**Comment by orangy** [comment]
Fixed
