### ISSUE TITLE
maven/gradle access of ktor-core does not work

### ISSUE THREAD

**Issue by rflauer** [Kotlin/ktor#83]
I keep getting a RuntimeException in the repo indexing. Some Google results suggest that that is an Intellij IDEA issue. Anyone else had that problem?

I use a 2017 version of Idea, without an external gradle installation. I tried version LATEST as well as some version numbers. Did anyone integrate ktor successfully with Maven/Gradle? I would be grateful for any hint because this seems to be a really useful project.

**Comment by yole** [comment]
This is indeed an IDEA issue. The RuntimeException doesn't prevent you from compiling your project in any way.
