### ISSUE TITLE
Request TwigFeature 

### ISSUE THREAD

**Issue by jmfayard** [Kotlin/ktor#84]
It would be great to be able to write `twig` templates (not a fan of freemarker :)

https://github.com/jtwig/jtwig

**Comment by orangy** [comment]
Can you may be contribute support for it? It shouldn't be too hard.

**Comment by jmfayard** [comment]
I will give it a try

**Comment by orangy** [comment]
Did you get it working?

**Comment by jmfayard** [comment]
I made a quick local test and looked how free marker support was implemented. That looks straightforward enough. I think I can work on that before the end of the week

**Comment by orangy** [comment]
Great!

**Comment by BoD** [comment]
@jmfayard I'm looking at Jtwig right now and was wondering if you got the chance to make a PR in the end?
