### ISSUE TITLE
Is ktor the replacement of kara?

### ISSUE THREAD

**Issue by gonejack** [Kotlin/ktor#87]
I am familiar with PHP and NodeJS, now new to kotlin, want to learn kotlin with real code instead of official tutorial which kind of boring , so search kotlin web framework on google and kara pops up, but kara seems deprecated and out of maintaining, isn't it?

should I get start with ktor instead? or kara is still fine?

**Comment by hhariri** [comment]
Ktor is an alternative to Kara that a few of us are working on (there's also Wasabi that is now joined forces with Ktor). If you're looking for a Kotlin framework that allows for HTTP-based applications, then Ktor might fit your needs.
