### ISSUE TITLE
Samples not compatible with latest IntelliJ

### ISSUE THREAD

**Issue by gonejack** [Kotlin/ktor#88]
Clone this repository down  and open ktor/ktor-samples/ktor-samples-hello with latest Intellij, after Maven auto-import and those automatically actions, added repository and dependency to pom.xml with you wrote on README.md, and troubles comes out.

There are some errors I am not sure cause by what,  IntelliJ or the sample code, but the base incorrect point is

```
<parent>
        <artifactId>ktor-samples</artifactId>
        <groupId>org.jetbrains.ktor</groupId>
        <version>0.3.2-SNAPSHOT</version>
</parent>
```

there is no version "snapshot" in Maven repository at the first, and the kotlin version is trouble too, those samples expecting kotlin 1.0.7 and IntelliJ come with 1.1.1. 

Can't express clearly, could you take a try. it take a few time to solve those errors, could you update this samples to be compatible with latest IntelliJ help people take a easy start up.

**Comment by orangy** [comment]
Please join our [Slack](kotl.in/slack) channel #ktor for support questions. From what I see, you probably tried to open sample directory in IDEA, you need to open `ktor` directory so that Maven can link together all modules.
