### ISSUE TITLE
NumberFormatException in routing with Locations

### ISSUE THREAD

**Issue by spand** [Kotlin/ktor#92]
I have the following test case in `LocationsTest.kt`

```kotlin
    @location("/f/{id}/{name}/") class FLocation(val id: Int, val name: String)
    @location("/f/{id}/{name}/{offset}/") class FOLocation(val id: Int, val name: String, val offset: Int)
    @location("/f/m/foo") class TestLocation(val foo: String?)

    @Test fun `precendece routing`() = withLocationsApplication {
        application.routing {
            get<FLocation> {
                call.respond("1: plain")
            }
            get<FOLocation> {
                call.respond("2: offset")
            }
            get<TestLocation> {
                call.respond("3: test")
            }
        }
        urlShouldBeHandled("/f/m/foo", "3: test")
    }
```
Produces a `java.lang.NumberFormatException: For input string: "m"`. I would have expected this to pass. Is it a bug or why is this ?

**Comment by orangy** [comment]
That's because `foo`, even if nullable, doesn't have default value and hence should be a parameter in query, like `/f/m/foo?foo=bar`. But if you add `= null` to foo parameter it still will loose to `/f/{id}/{name}` because match quality of missing parameter is low and beats better match quality of `/m` exact match to `{id}` parameter. 

Any suggestions are welcome.

**Comment by spand** [comment]
Ah yes. I forgot for a moment that `= null` isnt implied by the nullable type.

Thanks

**Comment by spand** [comment]
Having thought about this a bit more it seems I would expect two things about this case:
* If the {id} paramter is not an Int then the url should not match that route - ie. same as if the route had not been installed. In a regex based router it would be something like to route("/f/{\d+}/{[^/]+}/"). Parameters not matching is not an exceptional case either so it shouldnt result in exceptions that get printed to the console (might be CallLogging but even then).
* A constant path segment should win over a dynamic one simply because it is more specific and specific should win over more general rules.

**Comment by orangy** [comment]
I agree that type-check could be there, but it's simply not designed how, e.g. not sure if it should miss the routing with a 404 given `/f/x/something` with the routing above. Or should issue some other 4xx error. 

As for constant vs non-constant, it's complicated. As of now, we check the quality of the whole route trie path, not just immediate child, and you do have parameter in the `/f/m/foo` route, it's just happens to be non-path parameter, and it's missing. Missing param qualifies lower than existing param, hence the result.

**Comment by orangy** [comment]
Consider routing like this:
```
routing {
   route("{id}") {
      accept("text/html") {
        get { … }
      }
   }
   route("{name}") {
      accept("application/json") {
        get { … }
      }
   }
}
```
