### ISSUE TITLE
WAR deployment

### ISSUE THREAD

**Issue by bjuretic** [Kotlin/ktor#93]
Hello,

is there a way to use Ktor for classical WAR-style deployment, instead of embedded server? We have some existing apps, and Ktor would need to live near them on the same app server.

Thanks.

**Comment by cy6erGn0m** [comment]
Sure, there is an example with proper web.xml 

https://github.com/Kotlin/ktor/tree/master/ktor-samples/ktor-samples-hello

**Comment by bjuretic** [comment]
Thanks, that will do.
