### ISSUE TITLE
Hello world not working

### ISSUE THREAD

**Issue by Dkhusainov** [Kotlin/ktor#97]
<img src="http://i.imgur.com/KrJGxYa.png"></img>
<img src="http://i.imgur.com/Ti2IRLr.png"></img>

When I try to add missing imports it can't find them. Ctrl + F on embeddedNettyServer it find noghing either.

**Comment by hhariri** [comment]
There's been a slight change and the documentation isn't updated yet. Please paste the following code in your main project and include ktor-netty as a dependency. Let me know if it works.

```kotlin
import org.jetbrains.ktor.application.call
import org.jetbrains.ktor.host.embeddedServer
import org.jetbrains.ktor.http.ContentType
import org.jetbrains.ktor.netty.Netty
import org.jetbrains.ktor.response.respondText
import org.jetbrains.ktor.routing.get
import org.jetbrains.ktor.routing.routing

fun main(args: Array<String>) {
    val server = embeddedServer(Netty, 8080) {
        routing {
            get("/") {
                call.respondText("Hello, world!", ContentType.Text.Html)
            }
        }
    }
    server.start(wait = true)
}
```

**Comment by Dkhusainov** [comment]
<img src="http://i.imgur.com/ocG1qO8.png"></img>

Still not working

**Comment by hhariri** [comment]
I don't see ktor-netty in your list of dependencies. Did you add it?

**Comment by Dkhusainov** [comment]
It is in my dependencies, as you can see in the project window on the left.I even opened a class from it. I would download if from maven, but Idea refuses to index your repository.

**Comment by cy6erGn0m** [comment]
@Dkhusainov could you please try to add import 
`import org.jetbrains.ktor.host.*` ?

**Comment by cy6erGn0m** [comment]
btw, I don't see ktor-netty in the dependencies tree.. and I wonder why do you have ktor-netty.jar just right in the project tree? shouldn't it be in dependencies subtree?

**Comment by hhariri** [comment]
@Dkhusainov as @cy6erGn0m mentions, I also don't see ktor-netty in the dependencies

**Comment by cy6erGn0m** [comment]
What `pom.xml` do you use? could you please provide it's content?

**Comment by Dkhusainov** [comment]
I had to add it manually because It failed to index _https://dl.bintray.com/kotlin/ktor_ for some reason But no it does, and it works. Thanks for help, you can close the issue.

**Comment by pinebud** [comment]
I think import the jar manually is not a good way although it works. I met the same issue with you, and after I update the IntelliJ IDEA Kotlin plugin from v1.0.0 to v1.0.4, the error is gone. You can have a try.
