### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by cchuang0425** [Kotlin/ktor#98]
Ktor uses its [own repository](http://dl.bintray.com/kotlin/ktor) and [Kotlinx](https://dl.bintray.com/kotlin/kotlinx/), so the wiki and README should update and add another maven repository for getting integrity dependencies.

**Comment by cy6erGn0m** [comment]
Do you use gradle?

**Comment by cchuang0425** [comment]
Yes. May I miss any configuration?

**Comment by cy6erGn0m** [comment]
No, you are right: additional repository is specified but gradle doesn't support importing repositories from external pom's. This is why it doesn't work.

**Comment by cy6erGn0m** [comment]
fixed in 4e4ccf080ae90663f4f444b5cbdc02ea53892ffa, see [README.md](/Kotlin/ktor/blob/master/README.md#gradle)
